### ISSUE TITLE
null safety

### ISSUE THREAD

**Issue by md84419** [Fethi1/Shadow#5]
Please could this project be updated so it works on Flutter 2.0.

https://www.youtube.com/watch?v=bvq7wbn4VAA

**Comment by Fethi-Hamdani** [comment]
Thank you so much for the reference,  I'm quite busy with exams right now, I'll start working on it as soon as possible

**Comment by Fethi-Hamdani** [comment]
@md84419 Sorry for being extremely late, i just published a null safe version, thank you so much
